=== AltaColina/robot-commando/RobotCommando.Shared/Json/Schemas/page-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "$id": "https://github.com/AltaColina/robot-commando/tree/main/RobotCommando.Shared/Json/Schemas/page-schema.json",
  "title": "JSON Schema for page format",

  "type": "object",

  "properties": {
    "number": {
      "type": "integer"
    },
    "location": {
      "type": "string",
      "enum": [
        "Unknown",
        "Current",
        "Capital City",
        "City of Industry",
        "City of Knowledge",
        "City of Pleasure",
        "City of Storms",
        "City of the Guardians",
        "City of the Jungle",
        "City of Worship"
      ]
    },
    "text": {
      "type": "string"
    },
    "text2": {
      "type": "string"
    },
    "choices": {
      "type": "array",
      "items": {
        "$ref": "D:\\Development\\robot-commando\\RobotCommando.Shared\\Json\\Schemas\\choice-schema.json"
      }
    },
    "items": {
      "type": "array",
      "items": {
        "$ref": "D:\\Development\\robot-commando\\RobotCommando.Shared\\Json\\Schemas\\item-schema.json"
      }
    },
    "robots": {
      "type": "array",
      "items": {
        "$ref": "D:\\Development\\robot-commando\\RobotCommando.Shared\\Json\\Schemas\\robot-schema.json"
      }
    },
    "monsters": {
      "type": "array",
      "items": {
        "$ref": "D:\\Development\\robot-commando\\RobotCommando.Shared\\Json\\Schemas\\monster-schema.json"
      }
    },
    "enemies": {
      "type": "array",
      "items": {
        "$ref": "D:\\Development\\robot-commando\\RobotCommando.Shared\\Json\\Schemas\\enemy-schema.json"
      }
    },
    "effects": {
      "type": "string"
    }
  }
}

=== AltaColina/robot-commando/RobotCommando.Shared.Tests/Json/Pages/24.json
{
  "$schema": "https://raw.githubusercontent.com/AltaColina/robot-commando/main/RobotCommando.Shared/Json/Schemas/page-schema.json",
  "number": 24,
  "location": "City of Industry",
  "text": "     This man-shaped robot is designed for dinosaur herding. It moves by walking. It has weapons for dealing with rogue dinosaurs, but they are not as powerful as those of a war robot.",
  "robots": [
    {
      "bonusMax": 0,
      "bonus": 0,
      "types": 2,
      "armorMax": 10,
      "armor": 10,
      "speedMax": "Average",
      "speed": "Average",
      "id": "be101296-6329-48eb-8db1-e7aee6c07109",
      "tag": "Robot",
      "name": "Cowboy",
      "description": "A man-shaped robot designed for dinosaur herding",
      "icon": ""
    }
  ],
  "choices": [
    {
      "link": 47,
      "text": "Check the light flyer."
    },
    {
      "link": 70,
      "text": "Chose a place to go.",
      "condition": "c.Robot is not null",
      "greyedoutIfDisabled": true
    }
  ]
}

=== AltaColina/robot-commando/RobotCommando.Shared.Tests/Json/Pages/17.json
{
  "$schema": "https://raw.githubusercontent.com/AltaColina/robot-commando/main/RobotCommando.Shared/Json/Schemas/page-schema.json",
  "number": 17,
  "location": "City of Knowledge",
  "text": "     Are looking for something in particular?",
  "choices": [
    {
      "link": 85,
      "text": "Go search something else.",
      "condition": "!c.Inventory.Contains(\"Cloak Model Reference\")"
    },
    {
      "link": 53,
      "text": "Search for the Cloak of Invisibility.",
      "condition": "c.Inventory.Contains(\"Cloak Model Reference\")"
    }
  ]
}

=== AltaColina/robot-commando/RobotCommando.Shared.Tests/Json/Pages/9.json
{
  "$schema": "https://raw.githubusercontent.com/AltaColina/robot-commando/main/RobotCommando.Shared/Json/Schemas/page-schema.json",
  "number": 9,
  "location": "City of Knowledge",
  "text": "     There are several robots here, all identical. They are similar to the Cowboy Robot that you used on your ranch, but more heavily armed and armoured, for use against the largest dinosaurs. These Super-Cowboy Robots move by walking. Each has weapons almost as powerful as those of a war robot.\r\n     You may take one of these robots if you like.",
  "robots": [
    {
      "bonusMax": 1,
      "bonus": 1,
      "types": 0,
      "armorMax": 14,
      "armor": 14,
      "speedMax": 2,
      "speed": 2,
      "abilities": [
        {
          "condition": "c.Other.Types.HasFlag(MechaTypes.Dinossaur)",
          "phase": 4,
          "effects": {
            "BeforeBattle": "c.Other.Skill -= 1",
            "AfterBattle": "c.Other.Skill += 1"
          },
          "tag": "TriggerAbility",
          "name": "Sonic Screamer",
          "description": "-1 skill to all enemy dinossaurs.",
          "icon": ""
        }
      ],
      "tag": "Robot",
      "name": "Super Cowboy",
      "description": "",
      "icon": ""
    }
  ],
  "choices": [
    {
      "link": 129,
      "text": "Get in your robot and cross the electro-fence."
    },
    {
      "link": 85,
      "text": "Go to the Administrative Building."
    },
    {
      "link": 150,
      "text": "Leave the Dinosaur Preserve."
    }
  ]
}

=== AltaColina/robot-commando/RobotCommando.Shared.Tests/Json/Pages/3.json
{
  "$schema": "https://raw.githubusercontent.com/AltaColina/robot-commando/main/RobotCommando.Shared/Json/Schemas/page-schema.json",
  "number": 3,
  "location": "City of Knowledge",
  "text": "     Because you are not familiar with this type of robot, you do not get the normal combat bonus with it - in fact, your skill is 1 less than usual while you use it. You realize you had better get out of there while you can.",
  "choices": [
    {
      "link": 147,
      "text": "Leave the College of War."
    }
  ]
}

=== AltaColina/robot-commando/RobotCommando.Shared.Tests/Json/Pages/8.json
{
  "location": "City of Storms",
  "text": "     The sea-coast is a narrow strip of sand, bounded on one side by the ocean and on the other side by steep cliffs. After a few minutes of travel, you see something ahead.\r\n     It is a huge herd of Brontosaurus dinosaurs.\r\n     Most of them are munching on seaweed thrown up by the storms, but a few are investigating something that glitters.",
  "text2": "     The sea-coast is a narrow strip of sand, bounded on one side by the ocean and on the other side by steep cliffs. After a few minutes of travel, you don't see anything special.",
  "choices": [
    {
      "link": 84,
      "text": "Investigate it yourself.",
      "condition": "!c.Page.IsVisited"
    },
    {
      "link": 144,
      "text": "Turn around and go back to the city."
    }
  ]
}

=== AltaColina/robot-commando/RobotCommando.Shared.Tests/Json/Pages/20.json
{
  "$schema": "https://raw.githubusercontent.com/AltaColina/robot-commando/main/RobotCommando.Shared/Json/Schemas/page-schema.json",
  "number": 20,
  "location": "City of Industry",
  "text": "     The whole sixth floor of the Centre seems to be a cross between a laboratory and a gymnasium. In the middle of the room is a device like a suit of armour.\r\n    Beside it is a sleeping fellow, somewhat battered around the face, in an athletic suit. After a little investigation, you find that the device on the floor is an experimental 'Amplifier Suit', designed to make its wearer almost as strong and last as a robot.",
  "choices": [
    {
      "link": 83,
      "text": "Try the Amplifier Suit."
    },
    {
      "link": 333,
      "text": "Try another floor instead."
    }
  ]
}

=== AltaColina/robot-commando/RobotCommando.Shared.Tests/Json/Pages/4.json
{
  "$schema": "https://raw.githubusercontent.com/AltaColina/robot-commando/main/RobotCommando.Shared/Json/Schemas/page-schema.json",
  "number": 4,
  "location": "Capital City",
  "text": "     The main encampment of the Karosseans is easy enough to find; they have taken over the city stadium. Even from a distance you can see flying robots wheeling overhead.",
  "choices": [
    {
      "link": 18,
      "text": "Approach in your robot."
    },
    {
      "link": 32,
      "text": "Go on foot."
    }
  ]
}

=== AltaColina/robot-commando/RobotCommando.Shared.Tests/Json/Pages/5.json
{
  "$schema": "https://raw.githubusercontent.com/AltaColina/robot-commando/main/RobotCommando.Shared/Json/Schemas/page-schema.json",
  "number": 5,
  "location": "City of the Jungle",
  "text": "     Your path takes you across a shallow swamp; the road is narrow, and the ground to either side looks soft and sticky. When you round a corner, you see a large dinosaur ahead of you. It is not a flesh-eater, but it does not seem disposed to get out of your way.",
  "choices": [
    {
      "link": 239,
      "text": "Fight it!"
    },
    {
      "link": 95,
      "text": "Leave the road."
    }
  ]
}
