=== AltaColina/robot-commando/RobotCommando.Shared/Json/Schemas/page-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "$id": "https://github.com/AltaColina/robot-commando/tree/main/RobotCommando.Shared/Json/Schemas/page-schema.json",
  "title": "JSON Schema for page format",

  "type": "object",

  "properties": {
    "number": {
      "type": "integer"
    },
    "location": {
      "type": "string",
      "enum": [
        "Unknown",
        "Current",
        "Capital City",
        "City of Industry",
        "City of Knowledge",
        "City of Pleasure",
        "City of Storms",
        "City of the Guardians",
        "City of the Jungle",
        "City of Worship"
      ]
    },
    "text": {
      "type": "string"
    },
    "text2": {
      "type": "string"
    },
    "choices": {
      "type": "array",
      "items": {
        "$ref": "D:\\Development\\robot-commando\\RobotCommando.Shared\\Json\\Schemas\\choice-schema.json"
      }
    },
    "items": {
      "type": "array",
      "items": {
        "$ref": "D:\\Development\\robot-commando\\RobotCommando.Shared\\Json\\Schemas\\item-schema.json"
      }
    },
    "robots": {
      "type": "array",
      "items": {
        "$ref": "D:\\Development\\robot-commando\\RobotCommando.Shared\\Json\\Schemas\\robot-schema.json"
      }
    },
    "monsters": {
      "type": "array",
      "items": {
        "$ref": "D:\\Development\\robot-commando\\RobotCommando.Shared\\Json\\Schemas\\monster-schema.json"
      }
    },
    "enemies": {
      "type": "array",
      "items": {
        "$ref": "D:\\Development\\robot-commando\\RobotCommando.Shared\\Json\\Schemas\\enemy-schema.json"
      }
    },
    "effects": {
      "type": "string"
    }
  }
}

=== AltaColina/robot-commando/RobotCommando.Shared.Tests/Json/Pages/23.json
{
  "$schema": "https://raw.githubusercontent.com/AltaColina/robot-commando/main/RobotCommando.Shared/Json/Schemas/page-schema.json",
  "number": 23,
  "location": "City of Pleasure",
  "text": "     Unfortunately, this experimental craft is different from all other robots you have handled. Its Combat Bonus of 2 does not count for you until you have been through two combats with it.",
  "choices": [
    {
      "link": 378,
      "text": "Leave the City of Pleasure."
    }
  ]
}

=== AltaColina/robot-commando/RobotCommando.Shared.Tests/Json/Pages/13.json
{
  "location": "City of Knowledge",
  "text": "     You enter the village and investigate. You find one useful robot, a Digger Robot. This slow but powerful machine rides on treads. It has a bulldozer blade on the front, a scoop-shovel on the back, and two large claws for lifting.",
  "robots": [
    {
      "bonusMax": 0,
      "bonus": 0,
      "types": 0,
      "armorMax": 16,
      "armor": 16,
      "speedMax": 1,
      "speed": 1,
      "abilities": [
        {
          "usages": -1,
          "effects": {
            "AfterRoll": "c.This.Roll -= 2",
            "BeforeHit": "c.This.Damage = 6",
            "AfterRound": "c.This.Damage = 2"
          },
          "tag": "ActiveAbility",
          "name": "Powerful Strike",
          "description": "Activate: -2 to roll. +4 damage on hit.",
          "icon": ""
        }
      ],
      "tag": "Robot",
      "name": "Digger",
      "description": "Slow, but powerful machine that runs on treads. Has a bulldozer blade on the front, a scoop-shovel on the back and two large claws for lifting.",
      "icon": ""
    }
  ],
  "choices": [
    {
      "link": 361,
      "text": "Explore somewhere else in the City of Knowledge."
    }
  ]
}

=== AltaColina/robot-commando/RobotCommando.Shared.Tests/Json/Pages/14.json
{
  "$schema": "https://raw.githubusercontent.com/AltaColina/robot-commando/main/RobotCommando.Shared/Json/Schemas/page-schema.json",
  "number": 14,
  "location": "City of Knowledge",
  "text": "     You stay in your robot and travel to the huge Thalian Museum. This is the largest museum in all the land; it is full of exhibits on every imaginable subject.\r\n\r\n     As you approach the museum, you keep a sharp watch, but you see no enemies. When you arrive, you park your robot in front of the building and walk up the steps, past a pair of carved stone dragons. The museum attendant is snoring, but the little Information Robot is alert. 'Can I help you?' it asks. What will you do:",
  "text2": "     You stay in your robot and travel to the huge Thalian Museum. This is the largest museum in all the land; it is full of exhibits on every imaginable subject.",
  "choices": [
    {
      "link": 36,
      "text": "Ask for military information.",
      "condition": "!c.Page.IsVisited"
    },
    {
      "link": 80,
      "text": "Ask for information on sleeping sickness.",
      "condition": "!c.Page.IsVisited"
    },
    {
      "link": 58,
      "text": "Ask for information on the Karosseans.",
      "condition": "!c.Page.IsVisited"
    },
    {
      "link": 102,
      "text": "Leave the museum.",
      "condition": "!c.Page.IsVisited"
    },
    {
      "link": 160,
      "text": "Keep going to the museum.",
      "condition": "c.Page.IsVisited"
    }
  ]
}
